-- ElRipley Database Schema - Unified Media Assets Domain
-- Purpose: Track all media assets uploaded to S3 (user uploads + Facebook mirrors)
-- Includes: storage quota tracking, AI descriptions, and prompt media relationships
-- Database: PostgreSQL
-- ================================================================
-- MEDIA ASSETS TABLES
-- ================================================================

-- Unified media assets table
-- Tracks ALL media in S3: user uploads, Facebook mirrors, etc.
-- Replaces old facebook_media_assets table (migration needed)
CREATE TABLE media_assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Owner of this media (required for quota tracking)
    -- For user uploads: the uploader
    -- For FB mirrors: the user whose agent fetched the media
    user_id VARCHAR(36) NOT NULL,
    
    -- Source differentiation
    -- 'user_upload' = User uploaded directly via API
    -- 'facebook_mirror' = Mirrored from Facebook URL by agent
    source_type VARCHAR(20) NOT NULL CHECK (source_type IN ('user_upload', 'facebook_mirror')),
    
    -- === Facebook mirror specific fields (NULL for user uploads) ===
    -- Used to maintain deduplication for FB assets
    fb_owner_type VARCHAR(50),      -- 'fan_page', 'page_scope_user', 'post', 'comment', 'message'
    fb_owner_id VARCHAR(255),       -- ID of the FB entity that owns this media
    fb_field_name VARCHAR(100),     -- Field/column name (e.g., 'avatar', 'photo_url', 'profile_pic')
    source_url TEXT,                -- Original Facebook URL
    source_hash VARCHAR(64),        -- SHA256/ETag for deduplication
    
    -- === Core media info ===
    media_type VARCHAR(20) NOT NULL DEFAULT 'image', -- image | video | audio
    s3_key VARCHAR(500) NOT NULL,
    s3_url TEXT NOT NULL,
    file_size_bytes BIGINT NOT NULL DEFAULT 0, -- For quota tracking
    mime_type VARCHAR(100),         -- e.g., 'image/jpeg', 'video/mp4'
    original_filename VARCHAR(500), -- Original filename (for user uploads)
    
    -- === Status & lifecycle ===
    status VARCHAR(20) NOT NULL DEFAULT 'ready', -- pending | ready | failed
    error_message TEXT,
    
    -- Retention policy aligned with S3 lifecycle rules (aws/lifecycle.json)
    -- 'one_day'     → ephemeral/one_day/    (1 day expiry)
    -- 'one_week'    → ephemeral/one_week/   (7 days expiry)
    -- 'two_weeks'   → ephemeral/two_weeks/  (14 days expiry)
    -- 'one_month'   → ephemeral/one_month/  (30 days expiry)
    -- 'permanent'   → permanent/            (no expiry, counts toward quota)
    retention_policy VARCHAR(30) NOT NULL DEFAULT 'one_day'
        CHECK (retention_policy IN ('one_day', 'one_week', 'two_weeks', 'one_month', 'permanent')),
    
    expires_at BIGINT, -- Epoch millis when asset expires (NULL for permanent)
    
    -- === AI-generated description ===
    -- For fallback when media becomes stale/expired
    -- Generated by small vision model before feeding to main agent
    description TEXT,
    description_model VARCHAR(100),      -- Model used to generate (e.g., 'gpt-4o-mini')
    description_generated_at BIGINT,     -- When description was generated
    
    -- === Additional metadata ===
    metadata JSONB,                      -- Any additional data (dimensions, duration, etc.)
    last_checked_at BIGINT,              -- Last S3 availability check
    
    -- === Timestamps ===
    created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT * 1000,
    updated_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT * 1000,
    
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ================================================================
-- USER STORAGE QUOTA TABLE
-- ================================================================

-- Track storage quota usage per user
-- Only 'permanent' retention media counts toward quota
CREATE TABLE user_storage_quotas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(36) NOT NULL UNIQUE,
    
    -- Current usage (bytes) - calculated from media_assets where retention_policy = 'permanent'
    -- Updated when: media is persisted, media is deleted, periodic reconciliation
    permanent_storage_used_bytes BIGINT NOT NULL DEFAULT 0,
    
    -- Storage limit (bytes) - can be adjusted per user based on subscription/plan
    -- Default: 500MB (524288000 bytes)
    permanent_storage_limit_bytes BIGINT NOT NULL DEFAULT 524288000,
    
    -- Timestamps
    last_reconciled_at BIGINT,  -- Last time quota was recalculated from actual media
    created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT * 1000,
    updated_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT * 1000,
    
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


-- ================================================================
-- MEMORY BLOCK MEDIA JUNCTION TABLE
-- ================================================================

-- Media attachments for memory blocks
-- Defined here (instead of 04_schema_suggest_response.sql) because it references media_assets
CREATE TABLE memory_block_media (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    block_id UUID NOT NULL REFERENCES memory_blocks(id) ON DELETE CASCADE,
    media_id UUID NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 1,  -- For <image index="X">
    created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT * 1000,
    
    UNIQUE(block_id, media_id)
);

