"""Trigger suggest response tool - invoke suggest_response agent from general agent."""

import time
import uuid
from typing import TYPE_CHECKING, Any, Dict

import asyncpg

from src.agent.tools.base import BaseTool, ToolCallContext, ToolResult
from src.api.openai_conversations.schemas import MessageResponse
from src.database.postgres.repositories import get_facebook_page_admins_by_user_id

if TYPE_CHECKING:
    from src.agent.suggest_response.orchestration.orchestrator import (
        SuggestResponseOrchestrator,
        SuggestResponseResult,
    )


TOOL_DESCRIPTION = """Trigger the suggest_response agent to generate or send a message for a Facebook conversation.

Use this tool when:
1. You want the suggest_response agent to send a message directly to a customer (set auto_send=true)
2. You have just responded to an escalation and want suggest_response to process that escalation immediately
3. You want to test how the suggest_response agent behaves — e.g. verify that a playbook, hint, or recent change produces the expected suggestions

Optional: pass 'hint' to inject raw instruction text into suggest_response's context (e.g. to test guidance before saving as a playbook).

The suggest_response agent can either:
- Call generate_suggestions: Produce message suggestions (optionally auto-sent via Graph API if auto_send=true)
- Call complete_task: Finish work without sending a message (e.g., handle escalation response, update strategy)

The suggest_response agent decides what to do based on the conversation context, escalation state, and page_memory policies — no explicit instructions needed unless you provide a hint.

Returns:
- suggestions: The actual message suggestions generated by the agent (so you can inspect the output)
- playbook_system_reminder: The playbook context that was injected into suggest_response for this run (so you can see which playbook rules influenced the suggestions)
- suggestion_count, auto_send_used, skipped, skip_reason, locked: Execution metadata

This makes the tool effective for testing: you can trigger suggest_response, then inspect both the suggestions it produced AND the playbook that drove them — confirming cause-and-effect between your playbooks/hints and the agent's output."""


class TriggerSuggestResponseTool(BaseTool):
    """Tool to trigger suggest_response agent from general agent."""

    def __init__(self, orchestrator: "SuggestResponseOrchestrator"):
        self.orchestrator = orchestrator

    @property
    def name(self) -> str:
        return "trigger_suggest_response"

    @property
    def definition(self) -> Dict[str, Any]:
        return {
            "type": "function",
            "name": "trigger_suggest_response",
            "description": TOOL_DESCRIPTION,
            "parameters": {
                "type": "object",
                "properties": {
                    "conversation_type": {
                        "type": "string",
                        "enum": ["messages", "comments"],
                        "description": "Type of Facebook conversation (messages = inbox, comments = post comments)",
                    },
                    "conversation_id": {
                        "type": "string",
                        "description": "Facebook conversation ID (facebook_conversation_messages.id or facebook_conversation_comments.id)",
                    },
                    "fan_page_id": {
                        "type": "string",
                        "description": "Facebook page ID (fan_pages.id)",
                    },
                    "auto_send": {
                        "type": "boolean",
                        "default": False,
                        "description": "If true, automatically send the first suggestion to the customer via Facebook Graph API. Use when you want direct delivery.",
                    },
                    "hint": {
                        "type": ["string", "null"],
                        "description": "Raw instruction text to inject into suggest_response context as guidance (e.g. for testing before writing playbooks). Optional.",
                    },
                },
                "required": [
                    "conversation_type",
                    "conversation_id",
                    "fan_page_id",
                ],
                "additionalProperties": False,
            },
        }

    async def execute(
        self,
        conn: asyncpg.Connection,
        context: ToolCallContext,
        arguments: Dict[str, Any],
    ) -> Any:
        """Execute trigger - call suggest_response orchestrator."""
        user_id = context.user_id
        conversation_type = arguments.get("conversation_type", "messages")
        conversation_id = arguments.get("conversation_id", "")
        fan_page_id = arguments.get("fan_page_id", "")
        auto_send = arguments.get("auto_send", False)
        hint = arguments.get("hint")

        # Resolve page_admin for Graph API delivery when auto_send=True
        page_admin = None
        page_admin_id = None
        page_admins = await get_facebook_page_admins_by_user_id(conn, user_id)
        for admin in page_admins or []:
            if str(admin.get("page_id")) == str(fan_page_id):
                page_admin = admin
                page_admin_id = str(admin.get("id"))
                break

        if auto_send and not page_admin:
            raise ValueError(
                f"No page admin found for fan_page_id={fan_page_id}. "
                "Cannot auto_send without page access token."
            )

        result: "SuggestResponseResult" = await self.orchestrator.trigger(
            user_id=user_id,
            conversation_type=conversation_type,
            conversation_id=conversation_id,
            fan_page_id=fan_page_id,
            trigger_source="general_agent",
            page_admin_id=page_admin_id,
            page_admin=page_admin,
            facebook_page_scope_user_id=None,
            auto_send=auto_send,
            hint=hint,
        )

        return {
            "success": not result.skipped and not result.locked,
            "history_id": result.history_id,
            "suggestions": result.suggestions,
            "suggestion_count": result.suggestion_count,
            "skipped": result.skipped,
            "skip_reason": result.skip_reason,
            "locked": result.locked,
            "auto_send_used": auto_send and bool(result.suggestions),
            "playbook_system_reminder": result.playbook_system_reminder,
        }

    def process_result(self, context: ToolCallContext, raw_result: Any) -> ToolResult:
        """Format result for general agent context."""
        if not isinstance(raw_result, dict):
            output_text = str(raw_result)
        else:
            lines = []
            if raw_result.get("success"):
                if raw_result.get("suggestion_count", 0) == 0 and not raw_result.get(
                    "skipped"
                ):
                    lines.append("**Task completed** — no customer reply needed.")
                if raw_result.get("suggestions"):
                    lines.append(
                        f"**Generated {raw_result['suggestion_count']} suggestion(s).**"
                    )
                    if raw_result.get("auto_send_used"):
                        lines.append("First suggestion was sent to the customer.")
                if raw_result.get("playbook_system_reminder"):
                    lines.append(
                        "**Playbook context injected into suggest_response:**\n"
                        + raw_result["playbook_system_reminder"]
                    )
                lines.append(f"History ID: {raw_result.get('history_id', 'N/A')}")
            else:
                if raw_result.get("skipped"):
                    lines.append(f"Skipped: {raw_result.get('skip_reason', 'unknown')}")
                elif raw_result.get("locked"):
                    lines.append(
                        "Conversation is locked (another request in progress)."
                    )
                else:
                    lines.append("Trigger did not complete successfully.")
            output_text = "\n".join(lines) if lines else str(raw_result)

        output_message = MessageResponse(
            id=str(uuid.uuid4()),
            conversation_id=context.conv_id,
            sequence_number=0,
            type="function_call_output",
            role="tool",
            content=None,
            call_id=context.call_id,
            function_output=output_text,
            status="completed",
            metadata={"source": "trigger_suggest_response", "raw": raw_result},
            created_at=int(time.time() * 1000),
            updated_at=int(time.time() * 1000),
        )
        return ToolResult(
            output_message=output_message,
            human_message=None,
            metadata=None,
        )
